export const GET_ALL_JINGLES_REQUEST = 'GET_ALL_JINGLES_REQUEST';
export const GET_ALL_JINGLES_SUCCESS = 'GET_ALL_JINGLES_SUCCESS';
export const GET_ALL_JINGLES_FAILURE = 'GET_ALL_JINGLES_FAILURE';

export const WRAP_JINGLE_REQUEST = 'WRAP_JINGLE_REQUEST';
export const WRAP_JINGLE_SUCCESS = 'WRAP_JINGLE_SUCCESS';
export const WRAP_JINGLE_FAILURE = 'WRAP_JINGLE_FAILURE';
