export const GET_ALL_USER_JINGLES_REQUEST = 'GET_ALL_USER_JINGLES_REQUEST';
export const GET_ALL_USER_JINGLES_SUCCESS = 'GET_ALL_USER_JINGLES_SUCCESS';
export const GET_ALL_USER_JINGLES_FAILURE = 'GET_ALL_USER_JINGLES_FAILURE';

export const GET_ALL_USER_V0_JINGLES_REQUEST = 'GET_ALL_USER_V0_JINGLES_REQUEST';
export const GET_ALL_USER_V0_JINGLES_SUCCESS = 'GET_ALL_USER_V0_JINGLES_SUCCESS';
export const GET_ALL_USER_V0_JINGLES_FAILURE = 'GET_ALL_USER_V0_JINGLES_FAILURE';

export const GET_ALL_USER_V1_JINGLES_REQUEST = 'GET_ALL_USER_V1_JINGLES_REQUEST';
export const GET_ALL_USER_V1_JINGLES_SUCCESS = 'GET_ALL_USER_V1_JINGLES_SUCCESS';
export const GET_ALL_USER_V1_JINGLES_FAILURE = 'GET_ALL_USER_V1_JINGLES_FAILURE';

export const WRAP_JINGLE_REQUEST = 'WRAP_JINGLE_REQUEST';
export const WRAP_JINGLE_SUCCESS = 'WRAP_JINGLE_SUCCESS';
export const WRAP_JINGLE_FAILURE = 'WRAP_JINGLE_FAILURE';
export const CLEAR_WRAP_JINGLE = 'CLEAR_WRAP_JINGLE';

export const GET_ALL_OG_WRAPPED_USER_JINGLES_REQUEST = 'GET_ALL_OG_WRAPPED_USER_JINGLES_REQUEST';
export const GET_ALL_OG_WRAPPED_USER_JINGLES_SUCCESS = 'GET_ALL_OG_WRAPPED_USER_JINGLES_SUCCESS';
export const GET_ALL_OG_WRAPPED_USER_JINGLES_FAILURE = 'GET_ALL_OG_WRAPPED_USER_JINGLES_FAILURE';

export const GET_ALL_NEW_WRAPPED_USER_JINGLES_REQUEST = 'GET_ALL_NEW_WRAPPED_USER_JINGLES_REQUEST';
export const GET_ALL_NEW_WRAPPED_USER_JINGLES_SUCCESS = 'GET_ALL_NEW_WRAPPED_USER_JINGLES_SUCCESS';
export const GET_ALL_NEW_WRAPPED_USER_JINGLES_FAILURE = 'GET_ALL_NEW_WRAPPED_USER_JINGLES_FAILURE';

export const UNWRAP_JINGLE_REQUEST = 'UNWRAP_JINGLE_REQUEST';
export const UNWRAP_JINGLE_SUCCESS = 'UNWRAP_JINGLE_SUCCESS';
export const UNWRAP_JINGLE_FAILURE = 'UNWRAP_JINGLE_FAILURE';
export const CLEAR_UNWRAP_JINGLE = 'CLEAR_UNWRAP_JINGLE';

export const GET_USER_SAMPLES_REQUEST = 'GET_USER_SAMPLES_REQUEST';
export const GET_USER_SAMPLES_SUCCESS = 'GET_USER_SAMPLES_SUCCESS';
export const GET_USER_SAMPLES_FAILURE = 'GET_USER_SAMPLES_FAILURE';
