export const GET_SINGLE_JINGLE_REQUEST = 'GET_SINGLE_JINGLE_REQUEST';
export const GET_SINGLE_JINGLE_SUCCESS = 'GET_SINGLE_JINGLE_SUCCESS';
export const GET_SINGLE_JINGLE_FAILURE = 'GET_SINGLE_JINGLE_FAILURE';
export const CLEAR_SINGLE_JINGLE = 'CLEAR_SINGLE_JINGLE';

export const PURCHASE_JINGLE_REQUEST = 'PURCHASE_JINGLE_REQUEST';
export const PURCHASE_JINGLE_SUCCESS = 'PURCHASE_JINGLE_SUCCESS';
export const PURCHASE_JINGLE_FAILURE = 'PURCHASE_JINGLE_FAILURE';
export const CLEAR_PURCHASE_JINGLE = 'CLEAR_PURCHASE_JINGLE';
