export const GET_SINGLE_JINGLE_REQUEST = 'GET_SINGLE_JINGLE_REQUEST';
export const GET_SINGLE_JINGLE_SUCCESS = 'GET_SINGLE_JINGLE_SUCCESS';
export const GET_SINGLE_JINGLE_FAILURE = 'GET_SINGLE_JINGLE_FAILURE';
