export const GET_SINGLE_JINGLE_REQUEST = 'GET_SINGLE_JINGLE_REQUEST';
export const GET_SINGLE_JINGLE_SUCCESS = 'GET_SINGLE_JINGLE_SUCCESS';
export const GET_SINGLE_JINGLE_FAILURE = 'GET_SINGLE_JINGLE_FAILURE';
export const CLEAR_SINGLE_JINGLE = 'CLEAR_SINGLE_JINGLE';

export const PURCHASE_JINGLE_REQUEST = 'PURCHASE_JINGLE_REQUEST';
export const PURCHASE_JINGLE_SUCCESS = 'PURCHASE_JINGLE_SUCCESS';
export const PURCHASE_JINGLE_FAILURE = 'PURCHASE_JINGLE_FAILURE';
export const CLEAR_PURCHASE_JINGLE = 'CLEAR_PURCHASE_JINGLE';

export const SET_JINGLE_SALE_PRICE = 'SET_JINGLE_SALE_PRICE';
export const SELL_JINGLE_REQUEST = 'SELL_JINGLE_REQUEST';
export const SELL_JINGLE_SUCCESS = 'SELL_JINGLE_SUCCESS';
export const SELL_JINGLE_FAILURE = 'SELL_JINGLE_FAILURE';
export const CLEAR_SELL_JINGLE = 'CLEAR_SELL_JINGLE';

export const CANCEL_SALE_JINGLE_REQUEST = 'CANCEL_SALE_JINGLE_REQUEST';
export const CANCEL_SALE_JINGLE_SUCCESS = 'CANCEL_SALE_JINGLE_SUCCESS';
export const CANCEL_SALE_JINGLE_FAILURE = 'CANCEL_SALE_JINGLE_FAILURE';
export const CLEAR_CANCEL_SALE_JINGLE = 'CLEAR_CANCEL_SALE_JINGLE';
